language: generic
sudo: required
services: 
  - docker

before_install: 
  - docker build -t simkkish/docker-react -f Dockerfile.dev .

script: 
   - docker run -e CI=true simkkish/docker-react npm run test
